
Fixed a bug that caused a ``ModuleNotFoundError`` for *pkg_config* on
Python 3.12.
